import type { Metadata } from "next";
import { Providers } from "./provider"
import "./globals.css";



export const metadata: Metadata = {
  title: "Nnipa App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
